export { default as Home } from './Home'
export { default as Commands } from './Commands'
export { default as Profile } from './Profile'
export { default as Settings } from './Settings'
export { default as NotFound } from './NotFound'
